name: flutter_bloc_app_template
description: The project of the empty template with Flutter has built the basic framework to realize the functions of internationalization, theme peeling etc.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.3.0

  #* Intl Language
  intl: ^0.19.0
  intl_utils: ^2.8.7

  #* UI
  flutter_svg: ^2.0.10+1
  # cached_network_image: ^3.2.3
  google_fonts: ^6.2.1
  styled_text: ^8.1.0

  #* Networking
  alice: ^0.4.2
  dio: ^5.4.3+1
  http: ^1.2.1
  web_socket_channel: ^3.0.1

  #* File Systems
  file: ^7.0.0
  path_provider: ^2.1.3

  #* Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  #* State management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  #* Dart Data Class Genereation
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  #* Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.1


  #* Others
  flutter_keyboard_visibility: ^6.0.0
  # nullx: ^0.1.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.10
  injectable_generator: ^2.6.1
  flutter_gen_runner: ^5.5.0+1
  json_serializable: ^6.7.1
  #coverage: ^1.1.0
  lint: ^2.3.0
  mockito: ^5.4.4
  #test: ^1.17.9
  bloc_test: ^9.1.7
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
  freezed: ^2.4.7
  #dart_code_metrics: ^5.7.5
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    
  
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
